apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_ADAPTER
            value: postgres
          - name: DB_HOST
            value: postgres.kong.svc
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: kong
          - name: DB_PASSWORD
            value: kong
          - name: DB_DATABASE
            value: kong
        ports:
        - containerPort: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: konga-svc
spec:
  type: NodePort
  ports:
  - name: kong-proxy
    port: 1337
    targetPort: 1337
    nodePort: 30337
    protocol: TCP
  selector:
    app: konga
